### ISSUE TITLE
awsSignatureV4 undefined.

### ISSUE THREAD

**Issue by jhnlsn** [chilts/awssum-amazon-cloudsearch#1]
awssum-amazon-cloudsearch.js line 92-96 fails because awsSignatureV4 is undefined.

**Comment by chilts** [comment]
Hi John,

Removed those lines since we're now inheriting from amazon.AmazonSignatureV4 anyway.

Released to npm as v1.0.2.

Many thanks for reporting this issue. :)

Cheers,
Andy

**Comment by jhnlsn** [comment]
thanks
